### PR TITLE
Feature/15 css setup

### LINKED ISSUE #15: Set up CSS modules and Tailwind CSS

### PR DESCRIPTION
**Pull request by AllyMurray**
Implements #15

### CODE REVIEW

**Review by phobos665 — APPROVED** [review]
Looks good. One thing I need to do is check over tailwind and some of those class lists are very long, example: className="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3"

**Comment by AllyMurray** [comment]
@DanielAJoyce That's one of the downsides of the utility class approach. It's quite modular and if you want the styles applied you need the classes.

**Comment by phobos665** [comment]
> @DanielAJoyce That's one of the downsides of the utility class approach. It's quite modular and if you want the styles applied you need the classes.

That's fair. I think what might be nice is we can eventually makes these into components if they are re-used for better readability.

**Comment by AllyMurray** [comment]
> > @DanielAJoyce That's one of the downsides of the utility class approach. It's quite modular and if you want the styles applied you need the classes.
> 
> That's fair. I think what might be nice is we can eventually makes these into components if they are re-used for better readability. 

Yeah absolutely, the plan was to break things down when the designs are done and we have a good idea of what's required.

**Pull request merged**
